### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by Panchero** [xvzc/SpoofDPI#135]
Tell me, please, is there a command to delete the script? Safari doesn't work correctly

**Comment by kurtalex** [comment]
Spoof-DPI is in the folder: 
~/.spoof-dpi
You can remove the folder:
rm -rf ~/.spoof-dpi
But you can also terminate the terminal where open the service and it will be stopped
![spoof-dpi](https://github.com/user-attachments/assets/b8f8971f-8497-41c0-8a2d-f471fe0c3772)

**Comment by luixo** [comment]
Probably, instruction on removing system-wide proxy settings should be added as well.

**Comment by Dachneg** [comment]
Safari may not work because of enabled proxy on 12.7.0.0.1 8080

**Comment by xvzc** [comment]
If you quit spoof-dpi not in a normal way, the system proxy setting might not get rolled back properly. in those cases you can easily turn on the spoof-dpi again and press `Ctrl + c` to quit spoof-dpi. because that's the way how we quit terminal program.

Maybe next i have to add an inline instruction to the application like
INFO[2024-08-15T19:43:21+09:00] Press Ctrl + c to quit the server
