### ISSUE TITLE
Caching dns client

### ISSUE THREAD

**Issue by amanakin** [xvzc/SpoofDPI#149]
Hi there!
I see, that doh client is cached via sync.Once.
But custom dns client is created on every dns request.

WDYT if we will cache dns client too?
https://github.com/xvzc/SpoofDPI/blob/ab4d6819c7f8f82fb3f58cbc2ec2ff34af853948/dns/dns.go#L58

Assign me, if you think this is a good idea.

**Comment by ohaiibuzzle** [comment]
No. This is not an issue. The reason is that Go is garbage collected at runtime so when these go out of scope they're released.

And this is not even a cache. It's just that I wanted to use a singleton pattern for the DoH resolver. It could live perfectly fine not doing so.

Caching is being (partially) done here: #137

**Comment by amanakin** [comment]
> No. This is not an issue. The reason is that Go is garbage collected at runtime so when these go out of scope they're released, and since Go is compiled, performance isn't really an issue here.

Yes, I meant using a singleton DNS client 🙂. 
It might not be a significant issue now since you're using DNS over UDP. However, if you decide to add an option for DNS over TCP in the future, avoiding multiple handshakes and resource allocations could be beneficial.
I'll close the issue, thanks for the answer)
